apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resource:
    request:
      storage: 10Gi
  storageClassName: standard-rwo
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
      - name: local
        hostPath:
          path: /meubanco/
 
 ---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: http
  selector:
    app: mysql
  clusterIP: none
          
