apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resource:
    request:
      storage: 10Gi
  storageClassName: standard-rwo
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: marianaperola/projeto-mysql:2.0
        arg:
        - "--ignore-db-dir=lost+found"
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
      - name: local
        hostPath:
          path: /meubanco/
 ---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: none
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: marianaperola/projeto-backend:2.0
      imagePullPolicy: Always
      port:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: php
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php
  type: LoadBalancer
